name: マイグレーション

on:
  push:
    branches:
      - main

jobs:
  apply-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies & tooling
        run: |
          npm install

      - name: Apply migrations
        run: npm run drizzle:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}